#!/usr/bin/env bash
# Configures ubuntu to install nginx 

sudo apt-get update
sudo apt-get -y install nginx

sudo mkdir -p /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -t
sudo service nginx restart