#!/usr/bin/env bash
# Configures ubuntu to install nginx

sudo apt-get update
sudo apt-get -y install nginx

sudo mkdir -p /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

echo "server {
        listen 80;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html;
        location /redirect_me {
            return 301 https://www.linkedin.com/in/emmanuel-saah;
        }
        error_page 404 /custom_404.html;
        location = /custom_404.html {
            internal;
        }
}" > /etc/nginx/sites-available/default
sudo nginx -t
sudo service nginx restart