#!/usr/bin/env bash
# Displays 'Best School' 10 times and 'Hi' on the 9th

count=1

while [ $count -le 10 ];
do
	if [ $count -eq 9 ];
	then
		echo "Hi"
	else
		echo "Best School"
	fi

	((count++));
done