#!/usr/bin/env bash
# Configures and installs firewall

sudo apt update
sudo apt install ufw

sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw enable
